{
 "title": "Housing API Dashboard",
 "tags": [
  "housing",
  "mlops",
  "api"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(housing_api_requests_total[5m])"
    }
   ]
  },
  {
   "title": "95th Percentile Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(housing_api_request_duration_seconds_bucket[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Prediction Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(housing_api_predictions_total[5m])"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "housing_api_active_requests" }
   ]
  },
  {
   "title": "Median Prediction Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(housing_api_prediction_value_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Retraining Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(housing_api_retrain_total[5m])"
    }
   ]
  },
  {
   "title": "Success Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(housing_api_requests_total{status=\"200\"}[5m]) / rate(housing_api_requests_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Median Retraining Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(housing_api_retrain_duration_seconds_bucket[5m]))"
    }
   ]
  }
 ]
}